name: Live the Fringe
favicon: null
layout_spectrum: 0.91346
typography_spectrum: 0.04652
title: "LIVE the Fringe \\m/ LOVE the Fringe"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2560b0'
    - '#aae1fc'
    - '#c63005'
    - '#fdb94d'
    - '#c2765c'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
