name: Live the Fringe
favicon: null
layout_spectrum: 0.379594475729391
typography_spectrum: 0.3517315275967121
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.27446265635080636
  lightness: 0.3027075813151896
  saturation: 0.38411490339785814
  rhythmicContrast: 0.9172453326173127
purpose: []
